version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT_ALLOW_RESET=true
      # Uncomment and set as needed
      # QDRANT__SERVICE__HOST=0.0.0.0
      # QDRANT__SERVICE__HTTP_PORT=6333
